server:
  port: ${BACKEND_PORT}
  servlet:
    context-path: "/api/v1"

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
